import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import ThemeLayout from '@/components/ThemeLayout';

import './globals.scss';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'ML Models',
	description: 'Generated by create next app',
	icons: [
		{
			url: '/bee.svg',
			href: '/bee.svg',
		},
	],
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<ThemeLayout>{children}</ThemeLayout>
			</body>
		</html>
	);
}
