import type { Metadata } from 'next';
import { IBM_Plex_Sans } from 'next/font/google';

import ThemeLayout from '@/components/ThemeLayout';

import './globals.scss';

const ibmPlexSans = IBM_Plex_Sans({ weight: ['100', '200', '300', '400', '500', '600', '700'], subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'ML Models',
	description: 'Generated by create next app',
	icons: [
		{
			url: '/bee.svg',
			href: '/bee.svg',
		},
	],
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={ibmPlexSans.className}>
				<ThemeLayout>{children}</ThemeLayout>
			</body>
		</html>
	);
}
